# Generated by Django 5.1.1 on 2024-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='inscrit',
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
    ]
