# Generated by Django 5.1.1 on 2024-09-30 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_filiere_departement_filiere_inscrit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='inscrit',
        ),
        migrations.AlterField(
            model_name='student',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='auth_app.filiere'),
            preserve_default=False,
        ),
    ]
