# Generated by Django 5.1.1 on 2024-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_filiere_inscrit_alter_student_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
