# Generated by Django 5.1.1 on 2024-10-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_filiere_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploidetemps',
            name='test',
        ),
    ]
