# Generated by Django 5.1.1 on 2024-10-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_emploidetemps_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateField()),
                ('mois', models.CharField(blank=True, max_length=200, null=True)),
                ('inscrits', models.FloatField()),
            ],
        ),
    ]
