# Generated by Django 5.1.1 on 2024-10-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='mois',
            new_name='nom_session',
        ),
    ]
