# Generated by Django 5.1.1 on 2024-10-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_session_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='nom_session',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
