# Generated by Django 5.1.1 on 2024-10-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_session_nom_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_session',
            field=models.DateTimeField(),
        ),
    ]
