# Generated by Django 5.1.1 on 2025-07-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_session_date_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=200)),
                ('coef', models.FloatField(default=1.0)),
                ('note_cc', models.FloatField(blank=True, null=True, verbose_name='Contrôle Continu')),
                ('note_sn', models.FloatField(blank=True, null=True, verbose_name='Session Normale')),
                ('moyenne', models.FloatField(blank=True, null=True, verbose_name='Note finale')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.student')),
            ],
        ),
    ]
