# Generated by Django 5.1.1 on 2025-07-28 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_sujet_notification_sujetcommentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to=settings.AUTH_USER_MODEL),
        ),
    ]
