# Generated by Django 5.1.1 on 2025-07-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_alter_sujet_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
