# Generated by Django 5.1.1 on 2025-07-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_sujet_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementscolarite',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.filiere'),
        ),
        migrations.AddField(
            model_name='paiementscolarite',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.session'),
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='auth_app.filiere')),
            ],
        ),
        migrations.AlterField(
            model_name='paiementscolarite',
            name='tranche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.tranche'),
        ),
    ]
