# Generated by Django 5.1.1 on 2025-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_paiementscolarite_filiere_paiementscolarite_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementscolarite',
            name='montant_total',
        ),
        migrations.AddField(
            model_name='filiere',
            name='montant_global',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant global de la filière'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='nature_paiement',
            field=models.CharField(choices=[('inscription', 'tranche1'), ('tranche2', 'Tranche3')], default='tranche', max_length=20, verbose_name='Nature du paiement'),
        ),
    ]
