# Generated by Django 5.1.1 on 2025-07-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_remove_paiementscolarite_montant_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='nature_paiement',
            field=models.CharField(choices=[('Espece', 'Espèce'), ('Banque', 'Banque'), ('OM/MOMO', 'OM/MOMO'), ('Micro-finance', 'Micro-finance')], default='tranche', max_length=20, verbose_name='Nature du paiement'),
        ),
    ]
