# Generated by Django 5.1.1 on 2025-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_alter_filiere_nature_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='nature_paiement',
        ),
        migrations.AddField(
            model_name='paiementscolarite',
            name='nature_paiement',
            field=models.CharField(choices=[('Espece', 'Espèce'), ('Banque', 'Banque'), ('OM/MOMO', 'OM/MOMO'), ('Micro-finance', 'Micro-finance')], default='Espece', max_length=20, verbose_name='Nature du paiement'),
        ),
    ]
