# Generated by Django 5.1.1 on 2025-07-30 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_remove_filiere_nature_paiement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='auteur',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='cours',
            new_name='creneau_horaire',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='specialite',
        ),
        migrations.AddField(
            model_name='matiere',
            name='bareme',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.filiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='unite_enseignement',
            field=models.CharField(default='UE1', max_length=100),
        ),
        migrations.AddField(
            model_name='professeur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.matiere'),
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
    ]
