# Generated by Django 5.1.1 on 2025-07-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_remove_cours_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.professeur'),
        ),
    ]
