# Generated by Django 5.1.1 on 2025-07-31 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_matiere_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.professeur'),
        ),
    ]
