# Generated by Django 5.1.1 on 2025-07-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_alter_matiere_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
