# Generated by Django 5.1.1 on 2025-08-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_salle_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitejour',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.professeur'),
        ),
        migrations.AddField(
            model_name='activitejour',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.salle'),
        ),
        migrations.AlterField(
            model_name='activitejour',
            name='emploi_de_temps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='auth_app.emploidetemps'),
        ),
        migrations.AlterField(
            model_name='activitejour',
            name='jour',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='activitejour',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere'),
        ),
    ]
