# Generated by Django 5.1.1 on 2025-08-01 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_activitejour_professeur_activitejour_salle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitejour',
            options={'ordering': ['jour', 'heure_debut'], 'verbose_name_plural': 'Activités journalières'},
        ),
        migrations.AlterModelOptions(
            name='emploidetemps',
            options={'ordering': ['-date_debut', '-date_fin'], 'verbose_name_plural': 'Emplois du temps'},
        ),
        migrations.AddField(
            model_name='emploidetemps',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emploidetemps',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activitejour',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activitejour',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='auth_app.matiere'),
        ),
        migrations.AlterField(
            model_name='activitejour',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='auth_app.professeur'),
        ),
        migrations.AlterField(
            model_name='activitejour',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='auth_app.salle'),
        ),
        migrations.AlterField(
            model_name='emploidetemps',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='auth_app.filiere'),
        ),
    ]
