# Generated by Django 5.1.1 on 2025-08-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_alter_activitejour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidetemps',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='auth_app.session'),
        ),
    ]
