# Generated by Django 5.1.1 on 2025-08-05 14:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_emploidetemps_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('student', 'matiere')},
        ),
        migrations.AddField(
            model_name='note',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='note',
            name='delivre_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_delivrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='notes/pdf/'),
        ),
        migrations.AddField(
            model_name='note',
            name='mention',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Très bien', 'Très bien'), ('Bien', 'Bien'), ('Assez bien', 'Assez bien'), ('Passable', 'Passable'), ('Insuffisant', 'Insuffisant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_cc',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Contrôle Continu'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_sn',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Session Normale'),
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_attestation', models.CharField(choices=[('scolarite', 'Attestation de scolarité'), ('reussite', 'Attestation de réussite'), ('stage', 'Attestation de stage'), ('fin_etudes', "Attestation de fin d'études")], max_length=30)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('texte_personnalise', models.TextField(blank=True, null=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='attestations/')),
                ('valide_jusqua', models.DateField(blank=True, null=True)),
                ('delivre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_delivrees', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='auth_app.filiere')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='auth_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='ListePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cours', models.DateField(default=django.utils.timezone.now)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_presence', to='auth_app.filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_presence', to='auth_app.matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_presence', to='auth_app.professeur')),
            ],
            options={
                'ordering': ['-date_cours'],
            },
        ),
        migrations.RemoveField(
            model_name='note',
            name='coef',
        ),
        migrations.CreateModel(
            name='PresenceEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_present', models.BooleanField(default=True)),
                ('justification', models.CharField(blank=True, max_length=200, null=True)),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='auth_app.listepresence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='auth_app.student')),
            ],
            options={
                'unique_together': {('liste', 'student')},
            },
        ),
    ]
