# Generated by Django 5.1.1 on 2025-08-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_note_unique_together_note_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.filiere'),
        ),
    ]
