# Generated by Django 5.1.1 on 2025-08-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_note_filiere'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='presenceetudiant',
            constraint=models.UniqueConstraint(fields=('liste', 'student'), name='unique_student_per_list'),
        ),
    ]
