# Generated by Django 5.1.1 on 2025-08-07 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_presenceetudiant_unique_student_per_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='date_session',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='inscrits',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='nom_session',
        ),
        migrations.AddField(
            model_name='stat',
            name='date_calcul',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stat',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='auth_app.filiere'),
        ),
        migrations.AddField(
            model_name='stat',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='auth_app.session'),
        ),
        migrations.AddField(
            model_name='stat',
            name='total_femmes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='total_hommes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='total_inscrits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='total_reussite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
